name: main CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  LinuxBuild:
    runs-on: ubuntu-latest

    steps:
    # install deps
    - uses: actions/checkout@v2
    - name: install debian-packaged dependencies
      run: sudo apt install -y libwxgtk3.0-gtk3-dev libboost-graph1.74.0 libboost-serialization1.74.0 libboost-all-dev

    # build
    - name: build netlist-viewer 
      run: cd NetlistViewer/build/linux && make

   WindowsBuild:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: boost-date-time boost-system
          triplet: x64-windows-release
          token: ${{ github.token }}
